### ISSUE TITLE
Rooster inzien

### ISSUE THREAD

**Issue by ghost** [Z3r0byte/Magistify#11]
Als je je rooster in wilt zien, kun je momenteel alleen het rooster van vandaag bekijken, maar ik zou graag tussen de verschillende weekdagen willen bladeren om vooruit te kunnen kijken naar je toekomstige rooster.

**Comment by ghost** [comment]
@Z3r0byte 
Je zou dit kunnen doen door een balk onderaan het scherm te plaatsen met daarin twee pijlen om te navigeren tussen de verschillende dagen (zie low-res Paint-afbeelding die ik even gemaakt heb als (lelijk) voorbeeld, hieronder). Het tonen van de lessen kun je hetzelfde doen als hoe je het nu doet, en het enige wat je dus hoeft te doen is de datum veranderen tijdens je GET request.
![image](https://cloud.githubusercontent.com/assets/20394543/22406704/100124e4-e658-11e6-9d96-2316ff52ec8c.png)

**Comment by ghost** [comment]
@Z3r0byte Persoonlijk is dit een van mijn meest gewilde features aangezien ik graag kijk naar de lessen van morgen (vanwege uitval en tas inpakken) en ik zou het erg prettig vinden als je dit zou kunnen toevoegen

**Comment by Z3r0byte** [comment]
Ik zal er naar kijken nadat de eerste stable is uitgekomen :)

**Comment by ghost** [comment]
Graag! Dit lijkt me erg nuttig!

**Comment by Z3r0byte** [comment]
Update is binnen een uur online!

**Comment by ghost** [comment]
Fantastisch, nu heb ik nooit meer de langzame Magister app van schoolmaster te gebruiken!

**Comment by ghost** [comment]
Misschien zou je nog een knopje kunnen toevoegen waarmee je direct terug kunt gaan naar **vandaag**. Verder werkt het perfect!

**Comment by Z3r0byte** [comment]
Goed idee! Ik zal het in de volgende update toevoegen.

**Comment by Z3r0byte** [comment]
Het zit erin!
