### ISSUE TITLE
Cijferdetails

### ISSUE THREAD

**Issue by ghost** [Z3r0byte/Magistify#19]
Cijferdetails: Als je op het cijfer klikt zou je de omschrijving (proefwerk H2, etc.) en de weging van het cijfer kunnen tonen. Dit zou je ook als een ondertitel kunnen toevoegen aan het cijfer, maar dan wordt het een erg vol en onoverzichtelijk scherm.

**Comment by Z3r0byte** [comment]
Dit gaat moeilijk worden, aangezien Magister naast het cijfer en het vak niet het unieke ID van het cijfer stuurt, hierdoor is het moeilijk alle cijfer informatie te achterhalen.

**Comment by ghost** [comment]
@Z3r0byte Misschien begrijp ik het verkeerd, maar toen ik net een GET-request uitvoerde, zag ik het volgende:
![image](https://cloud.githubusercontent.com/assets/20394543/22344093/fbfa3954-e3fa-11e6-8d9b-26268c7616cf.png)

Het lijkt mij dus dat het 'CijferId', het cijfer ID is. Ook kreeg ik informatie zoals de docent, het vak, de datum en tijd, en de periode.

![image](https://cloud.githubusercontent.com/assets/20394543/22344135/3777247e-e3fb-11e6-8609-c5cbdd3f18a6.png)

**Comment by Z3r0byte** [comment]
@StanNL Het request wat jij uitvoerde is om alle cijfers te krijgen. Als je de nieuwe cijfers opvraagt, krijg je slechts de volgende gegevens:
![nieuwe cijfers](https://cloud.githubusercontent.com/assets/8726909/22345344/155fd4a8-e400-11e6-9ec2-555021dd83db.png)

**Comment by ghost** [comment]
@Z3r0byte Ik begrijp het probleem, maar misschien is het mogelijk om toch nog uit te voeren waar we het laatst over hadden: een cijfer-database. Hierdoor wordt de app wellicht een klein beetje minder efficiënt, maar als je gewoon bijvoorbeeld elk uur **alle** cijfers ophaalt en die toevoegt aan je database (inclusief metadata dus), blijft de app nog steeds snel en efficiënt, maar zijn er toch extra features mogelijk. Ik snap dat dit veel werk is, maar het is slechts een suggestie. Het zou dan wel nodig zijn om ook de metadata te vernieuwen als er een nieuw cijfer is.
