### ISSUE TITLE
Typfout?

### ISSUE THREAD

**Issue by ghost** [Z3r0byte/Magistify#23]
[Hier](https://github.com/Z3r0byte/Magistify/blob/9fa302dd620528239d71cb334e80a703fa61c160/.idea/copyright/profiles_settings.xml)
en [hier](https://github.com/Z3r0byte/Magistify/blob/9fa302dd620528239d71cb334e80a703fa61c160/.idea/copyright/Apche_2_0.xml) staat Apche (bij de tweede ook in de titel van het bestand), terwijl de naam voor deze licenses (als ik mij niet vergis) 'Apache' is.

**Comment by Z3r0byte** [comment]
Dit is inderdaad een typfout, maar dat maakt verder niks uit voor de 'werking' van de licentie. Maar toch bedankt voor je oplettendheid.
