### ISSUE TITLE
Testen donatie functie

### ISSUE THREAD

**Issue by Z3r0byte** [Z3r0byte/Magistify#24]
Hoi @StanNL,

Zou jij het leuk vinden om mee te helpen met het testen van de donatie functie? Zo ja, zou je dan een mailtje kunnen sturen naar z3r0byte.apps@gmail.com met daarin het gmail adres wat je gebruikt in de Play Store? Dan kan ik je toevoegen aan een lijst met testers zodat je **kosteloos** de donatie-functie kunt testen.

Groetjes,
Bas

**Comment by ghost** [comment]
@Z3r0byte Ik heb het verstuurd! Ik vond overigens een bug die ik zal uitleggen in issue #25

**Comment by ghost** [comment]
Ik wilde overigens ook even melden dat de gebundelde notificaties als er meerdere cijfers zijn, werken. Ik heb (helaas) geen screenshot ervan genomen, maar volgens mij was er niets mis mee. Ik wilde dit nog even zeggen aangezien het erg lastig is om te testen, omdat je niet vaak meerdere cijfers tegelijk krijgt.

**Comment by Z3r0byte** [comment]
Bedankt voor het melden van #25! Ik had de gebundelde notificaties zelf ook al getest dmv nep-cijfers, maar extra verificatie is altijd fijn! ;)

**Comment by ghost** [comment]
> Ik had de gebundelde notificaties zelf ook al getest dmv nep-cijfers

Hoe heb je dit eigenlijk gedaan? Heb je de http requests naar magister vervangen door requests naar je firebase database of heb je een andere methode gebruikt?

**Comment by Z3r0byte** [comment]
Ik heb gewoon statische cijfers aangemaakt in de code en deze aan de database toegevoegd. Via omleidingen zou het ook kunnen, maar dit was makkelijker.

**Comment by ghost** [comment]
Ik zie dat je weer actief bent op Github. Betekent dit dat er weer meer development komt? :crossed_fingers:

**Comment by Z3r0byte** [comment]
Zeker, de afgelopen weken was ik druk bezig met de toetsweek, vandaar de inactiviteit. :wink:

**Comment by ghost** [comment]
Dat is goed om te horen! Ik begrijp dat de proefwerkweek belangrijker is en ik heb hem net ook achter de rug.
