### ISSUE TITLE
Nieuwste Cijfer Bug

### ISSUE THREAD

**Issue by ghost** [Z3r0byte/Magistify#25]
Bij het 'Nieuwste Cijfer' laat hij niet altijd het nieuwste cijfer zien.
![image](https://cloud.githubusercontent.com/assets/20394543/21934448/b954ef1e-d9a9-11e6-93ce-a612bdbd3e28.png)
![image](https://cloud.githubusercontent.com/assets/20394543/21934471/ccbeca70-d9a9-11e6-8396-2391075b17fc.png)

**Comment by ghost** [comment]
@Z3r0byte Daarmee bedoel ik dat hij niet altijd het nieuwste cijfer laat zien **in het dashboard**, want in het nieuwste cijfer menu werkt het wel

**Comment by ghost** [comment]
Het wordt niet veel duidelijker of wel?

**Comment by Z3r0byte** [comment]
Jawel hoor, ik snap wat je bedoelt. :D

**Comment by ghost** [comment]
Okee mooi!

**Comment by Z3r0byte** [comment]
Bug is er weer. Ik ga proberen vandaag nog een bugfix te uploaden.

**Comment by Z3r0byte** [comment]
gefixed in 0.0.9

**Comment by ghost** [comment]
@Z3r0byte Vreemd genoeg is hij er nog steeds in versie 0.1.0 (en ook in 0.0.9). Kun je niet gewoon doen wat je doet in het cijfers-tabblad, want daar haal je alle nieuwe cijfers op en laat je ze één voor één zien. Kun je niet gewoon dat doen, maar dan alleen de bovenste uit het lijstje tonen?

**Comment by Z3r0byte** [comment]
Dat is eigenlijk wat hij ook zou moeten doen, vreemd genoeg heb ik inderdaad nu ook weer last van de bug.

**Comment by Z3r0byte** [comment]
Ik heb de database bekeken en gezien dat het ligt aan de manier van opslaan en niet het ophalen, ik verwacht vanavond een (hopelijk) definitive bugfix uit te brengen.

**Comment by ghost** [comment]
Het werkt!
