### ISSUE TITLE
Tabblad-Animatie

### ISSUE THREAD

**Issue by ghost** [Z3r0byte/Magistify#26]
De animatie voor het wisselen van tabbladen bij bijvoorbeeld 'Nieuwe Cijfers' is tegenstrijdig met de Material Design guidelines die de rest van de app wel aanhoudt. Dit klinkt wellicht een beetje vaag, maar hopelijk biedt de gif hieronder duidelijkheid over wat ik bedoel (sorry voor de lage framerates):
![Magistify](https://cloud.githubusercontent.com/assets/20394543/21954614/8db20812-da56-11e6-92b4-30cfac2598b4.gif)
Dit is bijvoorbeeld hoe de Android Authority app het doet:
![AA](https://cloud.githubusercontent.com/assets/20394543/21954615/95f2a734-da56-11e6-8741-602450adf324.gif)

**Comment by ghost** [comment]
@Z3r0byte De streep onder de naam van het tabblad verspringt als je swipet door de menu's. Normaal gesproken zou er een animatie zijn waarbij de streep geleidelijk verplaatst naarmate je je vinger over het scherm beweegt. (hopelijk is het nu iets duidelijker)

**Comment by Z3r0byte** [comment]
@StanNL De balk zou inderdaad mee moeten bewegen, maar helaas ondersteunt de library die ik daarvoor gebruikt het niet. Ik zal het nog ooit veranderen, maar op dit moment vind ik andere dingen belangrijker.

**Comment by ghost** [comment]
> Op dit moment vind ik andere dingen belangrijker.

Dat begrijp ik volledig maar het leek me toch handig om het te melden zodat je er in de toekomst wellicht nog naar zal kijken

**Comment by Z3r0byte** [comment]
Het was zeker fijn dat je dat meldde!
