### ISSUE TITLE
Force Close

### ISSUE THREAD

**Issue by ghost** [Z3r0byte/Magistify#28]
Met versie 0.0.7 bèta sluit de app automatisch bij het openen. Ik zal straks een syslog sturen zodra ik thuis ben.

**Comment by Z3r0byte** [comment]
Ik heb net even Firebase gechecked, er lijkt iets mis te zijn met het ophalen van de aankopen.

**Comment by Z3r0byte** [comment]
Is dit probleem er nog steeds?

**Comment by ghost** [comment]
Wel in versie 0.0.8

**Comment by ghost** [comment]
En ook in versie 0.0.9

**Comment by Z3r0byte** [comment]
Gebeurt dat altijd, of af en toe?

**Comment by ghost** [comment]
Dit gebeurt altijd

**Comment by ghost** [comment]
Op mijn tablet werkt de app daarentegen wel, terwijl die verbonden is met hetzelfde Google account. Dit kan betekenen dat het niet met de donaties te maken heeft, maar ik denk dat je er zelf nog maar even naar moet kijken

**Comment by Z3r0byte** [comment]
vreemd, ik heb nergens last van. Ik zal proberen een safe-guard in te bouwen.

**Comment by ghost** [comment]
De system logs melden het volgende:
```
01-26 19:53:45.162   856  1058 E AndroidRuntime: FATAL EXCEPTION: Thread-10
01-26 19:53:45.162   856  1058 E AndroidRuntime: Process: com.z3r0byte.magistify, PID: 856
01-26 19:53:45.162   856  1058 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'android.os.Bundle com.android.vending.billing.IInAppBillingService.getPurchases(int, java.lang.String, java.lang.String, java.lang.String)' on a null object reference
01-26 19:53:45.162   856  1058 E AndroidRuntime: 	at com.z3r0byte.magistify.DashboardActivity$9.run(DashboardActivity.java:382)
01-26 19:53:45.162   856  1058 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
```

**Comment by Z3r0byte** [comment]
Het zou opgelost moeten zijn in 0.1.0

**Comment by ghost** [comment]
Bedankt! Ik ga het gelijk proberen!

**Comment by ghost** [comment]
Het werkt! Ontzettend bedankt!
