### ISSUE TITLE
Set-up bug

### ISSUE THREAD

**Issue by ghost** [Z3r0byte/Magistify#29]
Als je de app installeert en je door de set-up geleid wordt, gaat de app weer terug naar de eerste pagina zodra je je school (zowel handmatig als automatisch) ingevoerd hebt. Zie gif hieronder voor meer duidelijkheid:
![magistify](https://cloud.githubusercontent.com/assets/20394543/22346709/62140ec2-e405-11e6-860b-2535c8cbe091.gif)
(dit komt **niet** doordat een gif automatisch opnieuw afspeelt, maar dit is echt wat er gebeurt)

Ik denk dat dit komt doordat er nu een nieuwe pagina is met de waarschuwing dat dit slechts tools zijn en geen volledige app. Hierdoor denkt de app als je bij de 5e pagina bent, dat de set-up al klaar is, en dan gaat hij naar het dashboard, maar er is nog niet ingelogd (dit is slechts een vermoeden).

**Comment by Z3r0byte** [comment]
Ik zie je report nu pas, maar ik was er zelf ook al achtergekomen en heb het al opgelost in versie 0.0.8. ;)

**Comment by Z3r0byte** [comment]
Je vermoeden was trouwens juist, dat was precies wat er gebeurde. :wink:

**Comment by ghost** [comment]
@Z3r0byte Mooi dat het is opgelost (en dat ik het goed geraden had natuurlijk ;) )
