### ISSUE TITLE
Uitgebreide notificaties

### ISSUE THREAD

**Issue by ghost** [Z3r0byte/Magistify#30]
Het is misschien leuk om uiteindelijk de notificaties gedetailleerder te maken. Zodra de app gemiddeldes ondersteunt kun je ook de verandering in het gemiddelde laten zien. Zoals dit:

1 nieuw cijfer
7.8 voor maatschappijleer
Je gemiddelde voor maatschappijleer is 0.1 omhoog gegaan naar 7.5

**Of:**

1 nieuw cijfer
7.5 voor maatschappijleer
Je gemiddelde voor maatschappijleer is gelijk gebleven, 7.4

**Of:**
1 nieuw cijfer
7.5 voor maatschappijleer
Je gemiddelde voor maatschappijleer is 0.1 omlaag gegaan naar 7.5.
Je totale gemiddelde is 0.1 omlaag gegaan naar 7.2

Dit is wel ingewikkeld, maar zodra je dus **alle** cijfers kunt zien (als dat ooit gaat gebeuren) en je ook alle gemiddeldes kunt zien, is dit een wijziging die niet heel lastig moet zijn (denk ik).

**Comment by ghost** [comment]
Dit was wel erg veel gevraagd trouwens. Deze issue kan gesloten worden.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Z3r0byte** [comment]
Oké, is goed hoor. Wie weet probeer ik het nog wel eens ;)
