### ISSUE TITLE
Tip: Roosterwijzigingen

### ISSUE THREAD

**Issue by ghost** [Z3r0byte/Magistify#31]
@Z3r0byte 
Volgens mij las ik ergens dat je ook ooit nog iets wilt doen met roosterwijzigingen. Dit is niet heel lastig, want Magister heeft dit standaard ingebouwd, de link hiervoor is:
> /api/personen/**id**/roosterwijzigingen?van=**datum**&tot=**datum**

Hopelijk heb je hier iets aan als je dit gaat implementeren in Magistify.

**Comment by Z3r0byte** [comment]
Hoi Stan, bedankt voor de tips. Ik wist dit zelf ook al aangezien dit ook in Magis zat. Maar toch bedankt :)

**Comment by Z3r0byte** [comment]
Op dit moment ben ik hier mee bezig ;)

**Comment by ghost** [comment]
Dat lijkt me erg handig en ik zou het graag voor je willen testen! Misschien kun je zelfs uiteindelijk notificaties geven als er nieuwe roosterwijzigingen zijn

**Comment by Z3r0byte** [comment]
Dat was ik inderdaad al van plan :)

**Comment by Z3r0byte** [comment]
Toetsweek komt er trouwens weer aan, dus verwacht de komende tijd niet heel veel activiteit. ;)

**Comment by ghost** [comment]
Daar heb ik zeker begrip voor

**Comment by Z3r0byte** [comment]
Mocht je je afvragen waarom er weer een tijdje niks is veranderd: ik ben nou aan het wachten tot ik kan gaan testen. Als het goed is kan ik morgen beginnen, want volgende week dinsdag zijn bij mij de eerste roosterwijzigingen, en je kan ze pas een week van te voren zien. ;)

**Comment by ghost** [comment]
@Z3r0byte Ik kan het voor je testen! Mijn school ziet deze vakantie als heel veel uitgevallen lessen. (Zie screenshot)![](http://i.imgur.com/quayIq8.png)

**Comment by Z3r0byte** [comment]
Bedankt voor je aanbod! Je kunt de bijgevoegde app installeren om te testen. (Ik moest hem zippen, omdat hij hem anders niet accepteerde ;) )
[app-debug.apk.zip](https://github.com/Z3r0byte/Magistify/files/971283/app-debug.apk.zip)

**Comment by Z3r0byte** [comment]
UPDATE: Ik heb zojuist een beta versie geupload naar de play store, dus je kunt hem nou ook daar downloaden :)

**Comment by ghost** [comment]
@Z3r0byte De app crasht bij de setup. 
Als ik mijn schoolnaam typ crasht hij.

**Comment by ghost** [comment]
@Z3r0byte Inmiddels werkt het weer

**Comment by ghost** [comment]
@Z3r0byte De roosterwijzigingen werken! Ze zijn alleen niet gesorteerd.
![](http://i.imgur.com/jVe0lRT.png)

**Comment by Z3r0byte** [comment]
@StanNL Dit komt doordat Magister de roosterwijzigingen zo aanlevert en de app ze direct weergeeft​. Maar ik ga waarschijnlijk toch een database gebruiken voor de notificaties, dus dan kan ik ze makkelijker ordenen.

**Comment by Z3r0byte** [comment]
@StanNL Dit probleem is in de nieuwste versie opgelost ;)

**Comment by ghost** [comment]
@Z3r0byte Mooi! Ik heb alleen geen wijzigen om het mee uit te testen

**Comment by ghost** [comment]
Fijn dat dit nu helemaal geregeld is! Misschien zou je binnenkort ooit kunnen kijken naar magister mails! (maar daar zit geen haast achter, natuurlijk)

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
