### ISSUE TITLE
Database doesn't save all grades

### ISSUE THREAD

**Issue by Z3r0byte** [Z3r0byte/Magistify#34]
The database doesnt save all new grades, which causes the dashboard (AGAIN! 😡) not to work well.

**Comment by ghost** [comment]
De cijfers op het dashboard werken bij mij prima. Ik heb vandaag 2 nieuwe cijfers gekregen en elke keer werd het dashboard geüpdatet.

**Comment by Z3r0byte** [comment]
Klopt maar als een leraar meerdere cijfers tegelijk invult, wordt alleen de eerste opgeslagen, want op dit moment kijkt hij alleen naar de invuldatum om dubbele cijfers te voorkomen.

**Comment by ghost** [comment]
Ah, ik begrijp het probleem. Dan zul je toch een ID moeten opvragen waar we het al eerder over hadden, bij #19

**Comment by Z3r0byte** [comment]
of gewoon het cijfer en het vak meenemen in de check :)

**Comment by ghost** [comment]
@Z3r0byte ja maar dit werkt niet als je twee keer hetzelfde cijfer hebt! (waarvan de kans vrij klein is, maar wel aanwezig)

**Comment by Z3r0byte** [comment]
Maar dan maakt het ook niet uit, want op het dashboard staat dan nog steeds het 'laatste' cijfer 😉 Had je mijn mail trouwens gehad?

**Comment by ghost** [comment]
Oh ja natuurlijk daar heb je helemaal gelijk in! Ik heb je mail overigens ontvangen, maar het versturen van het antwoord werkte niet vreemd genoeg. Ik zal de mail straks nogmaals (proberen te) sturen

**Comment by Z3r0byte** [comment]
Ik heb je antwoord ondertussen ontvangen :)
