### ISSUE TITLE
Dataverbruik

### ISSUE THREAD

**Issue by maikka39** [Z3r0byte/Magistify#43]
Magistify verbruikt in 1 dag ongeveer 33,4 MB aan data. Dit is wel een beetje veel voor een magister app, in magis is het maar 0,3 MB.

**Comment by Z3r0byte** [comment]
Dat klopt, zelf had ik dit ook al gezien. Dit komt omdat Magistify ook data op de achtergrond ophaalt, Magis niet. Ik ben op dit moment aan het kijken hoe ik het datagebruik kan verminderen ;)

**Comment by Z3r0byte** [comment]
Er is nu een optie om alleen data met wifi op de achtergrond op te halen
