### ISSUE TITLE
Roosterwijzigingen op dashboard

### ISSUE THREAD

**Issue by ghost** [Z3r0byte/Magistify#45]
Misschien is het een goed idee om de eerste drie (eventueel kun je dit getal instelbaar maken) aankomende roosterwijzigingen op het dashboard te tonen

**Comment by ghost** [comment]
De roosterwijziging-meldingen werken! Dat is erg goed nieuws. Nu kan ik morgenochtend testen of de "melding als volgende les gewijzigd is" functie werkt.

**Comment by Z3r0byte** [comment]
Ik zie je comment van 5 dagen geleden nu pas, sorry voor dat 😅. Het is inderdaad wel een goed idee om een paar roosterwijzigingen te laten zien.
En goed nieuws om te horen dat tot nu toe alles werkt! Als het goed is zou je de melding voor de komende les 25 minuten van te voren moeten krijgen.

**Comment by ghost** [comment]
@Z3r0byte Hmm dan zou ik hem inmiddels al gehad moeten hebben. Misschien komt het omdat de les uitgevallen is dus hij "bestaat niet meer".
Misschien is dit onmogelijk, maar is het mogelijk om ook de oude situatie te tonen in het roosterwijzigingen scherm?

_Sent from my Samsung kminilte using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Z3r0byte** [comment]
Dit zou moeilijk worden, omdat in de agenda ook al de bijgewerkte afspraken staan, je kunt dus niet gaan vergelijken.

**Comment by ghost** [comment]
@Z3r0byte Ja maar ik dacht dat de Magister API dit misschien ook meestuurde. De melding voor de volgende les werkt trouwens nog niet

_Sent from my Samsung kminilte using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Z3r0byte** [comment]
Oké, bedankt voor het doorgeven, ik zal kijken of ik vandaag tijd heb om het op te lossen.

**Comment by Z3r0byte** [comment]
De melding werkt in de nieuwste release als het goed is

**Comment by ghost** [comment]
@Z3r0byte Ja hij werkt!

_Sent from my Samsung Galaxy S5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Z3r0byte** [comment]
Mooi zo :)

**Comment by Z3r0byte** [comment]
Ik ben hiermee aan de slag gegaan, maar er zijn nog een paar bugs die moeten worden opgelost ;)

**Comment by Z3r0byte** [comment]
@StanNL UPDATE: ik heb de bugs als het goed is opgelost (moet het nog wel even testen op emulators), dus de update komt binnenkort (ook al heb je daar waarschijnlijk niet meer veel aan 😆 )

**Comment by ghost** [comment]
Het werkt helemaal. Hij toont de eerste drie roosterwijzigingen voor de komende schooldag. Het is echter zo dat de roosterwijzigingen activity niet opent als je op een individuele roosterwijziging tikt. Ook ontbreekt de schaduw van de card aan de onderkant. Verder werkt het heel goed!

**Comment by Z3r0byte** [comment]
@StanNL Dat van die schaduw klopt, en ik heb het ook geprobeerd op te lossen, maar na een uur proberen heb ik het opgegeven 😂. Ik zal nog een klikactie toevoegen aan de individuele roosterwijzigingen.

**Comment by Z3r0byte** [comment]
Ik zie trouwens dat de landscape layout nog niet klopt, ik zal die binnenkort verbeteren

**Comment by ghost** [comment]
Ik denk dat ik al zie waar het "schaduwprobleem" vandaan komt.
![](https://i.imgur.com/QldhHqB.png)
Aan de onderkant van de activity zit een grijze streep. Om het in CSS uit de drukken (omdat ik niks van Java afweet): De body heeft een te grote padding, of juist een margin. Als je die waardes tweakt, of als je die card een grotere margin-bottom geeft, denk ik dat je het probleem kunt oplossen.

**Comment by Z3r0byte** [comment]
Het heeft inderdaad iets met de margin te maken denk ik. Ik heb ook al met de margin en padding zitten spelen, maar zonder succes :(

**Comment by Z3r0byte** [comment]
De landscape view is zonder roosterwijzigingen, omdat ik het niet voor elkaar kreeg om die fatsoenlijk zonder overlap onder de cijfers en lessen widget te plaatsen
