### ISSUE TITLE
Agenda-afspraak details

### ISSUE THREAD

**Issue by ghost** [Z3r0byte/Magistify#46]
Ik heb dit al een eerdere keer aangekaart, maar het lijkt mij erg handig als je meer informatie over de afspraken kunt zien wanneer je erop klikt. Dingen zoals docent, maar vooral ook huiswerk, lijken me erg handig

_Sent from my Samsung kminilte using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Z3r0byte** [comment]
Dit ga ik mss implemteren, maar ik heb hier eigenlijk expres voor gekozen, omdat het originele plan was om geen volledige magister app van te maken. Ik mis dit zelf echter ook wel eens, dus ik zal er nog eens over nadenken

**Comment by ghost** [comment]
@Z3r0byte Bedankt voor het in overweging nemen

_Sent from my Samsung kminilte using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Z3r0byte** [comment]
Ik ga dit na versie 1.4.0 implementeren

**Comment by ghost** [comment]
@Z3r0byte Dat zou fantastisch zijn!

**Comment by Z3r0byte** [comment]
Ik heb zojuist 1.4.1 beta gepubliceerd waarin dit verwerkt is :).

**Comment by ghost** [comment]
Het werkt erg goed! Bedankt

_Sent from my Xperia XZ using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Z3r0byte** [comment]
Fijn om te horen!
