### ISSUE TITLE
Incorrect Activity Names

### ISSUE THREAD

**Issue by Laurenshup** [Z3r0byte/Magistify#49]
Als je op de melding klikt die je krijgt als je een nieuw punt hebt dan zie je de Activity Naam.
Als je op recente apps klikt, (menu knop) dan zie je daar de Activity Naam in plaats van Magistify.

**Comment by ghost** [comment]
@Laurenshup Ik kan dit ook bevestigen (Android 7.1.2)

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Z3r0byte** [comment]
Bedankt voor het melden, ik zal het oplossen! :)

**Comment by ghost** [comment]
Het geldt trouwens ook voor de roosterenmeldingen. Dan staat er AppointmentActivity. Als je vanuit deze Activity weer naar het dashboard gaat, crasht/sluit de app

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Z3r0byte** [comment]
Ik zal wel heel het Manifest doorkijken en die namen veranderen
