### ISSUE TITLE
Changed Login Protocol

### ISSUE THREAD

**Issue by Z3r0byte** [Z3r0byte/Magistify#51]
Schoolmaster updated their login procedure. The old method still works, but they might stop supporting it in the future.

**Comment by Z3r0byte** [comment]
I will start implementing this, so I can change methods quick when needed

**Comment by Z3r0byte** [comment]
My school shut down Magister till August 24th, so no update will be coming until at least then.

**Comment by ghost** [comment]
@Z3r0byte 24 augustus is al geweest :)

**Comment by Z3r0byte** [comment]
Klopt, en ik ben er ook mee bezig, maar het is echt een stuk ingewikkelder dan eerst ;)

**Comment by Z3r0byte** [comment]
Ik weet al welke requests ik moet sturen, maar het lijkt alsof ze een soort beveiliging hebben ingebouwd zodat niet iedereen die verzoeken kan sturen, later meer hierover

**Comment by Z3r0byte** [comment]
Het lijkt erop dat ze dit gebruiken: https://docs.microsoft.com/en-us/aspnet/web-api/overview/security/preventing-cross-site-request-forgery-csrf-attacks Als ik die tokens kan vinden, ben ik al weer een stuk verder. :)

**Comment by Z3r0byte** [comment]
Aangezien er nog steeds geen tekenen zijn dat de andere API wordt uitgeschakeld, gaat deze issue voorlopig op non-actief
