### ISSUE TITLE
Zijmenu werkt niet

### ISSUE THREAD

**Issue by ghost** [Z3r0byte/Magistify#54]
In het zijmenu is altijd het dashboard geselecteerd, ongeacht in welke Activity je zit. (ik gebruik versie 1.4.1)
![](https://i.imgur.com/axvIXUJ.png)

_Sent from my Xperia XZ using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Z3r0byte** [comment]
Oh ja ik zie het. Ik los het zo snel mogelijk op!
