### ISSUE TITLE
Bugs&Suggesties

### ISSUE THREAD

**Issue by ghost** [Z3r0byte/Magistify#6]
Hier stonden eerst de bugs en suggiesties

**Comment by StanNL** [comment]
De tijd naast de afspraak klopt niet
![screenshot_20170109-091609](https://cloud.githubusercontent.com/assets/20394543/21760452/7e46c1aa-d64c-11e6-9d92-affe4eec918a.png)

**Comment by Z3r0byte** [comment]
Bedankt voor het melden van de bugs via GitHub, dat is inderdaad fijner dan via Google Play. Ik heb op dit moment niet echt tijd voor een uitgebreide reactie, maar die zal ik later vandaag nog sturen.

**Comment by Z3r0byte** [comment]
Hoi @StanNL,
Hier alvast een reactie voor de bugs:

> Op het hoofdscherm is de eerstvolgende les erg raar gepositioneerd. Ik vermoed dat daar nog een getal hoort te staan dat aangeeft welke les volgt. Screenshot:

Daar hoort inderdaad nog een cijfer voor te staan. Ik zal het zsm oplossen.

> In landscape mode ziet het nieuwste cijfer er raar uit. Ik zou de twee cards met informatie naast elkaar plaatsen zodra je je telefoon draait. Screenshot:

Deze bug had ik zelf nog niet gevonden, bedankt voor het melden! Ook deze bug zal ik oplossen.

> Het tijdstip in de melding over je volgende vak klopt niet. Screenshot:

Hier was ik zelf ook al achtergekomen, het heeft te maken dat er nu een ' 0' voor de maand staat en de database kan daar niet zo goed tegen, waardoor je dit soort dingen krijgt. Deze bug heeft de hoogste prioriteit.


Gr.
Bas

**Comment by ghost** [comment]
> Bedankt voor het melden van de bugs via GitHub

Geen probleem! Aangezien ik de app vaak gebruik zal ik de komende tijd nog veel dingen opmerken tijdens dagelijks gebruik en die zal ik hier blijven melden. Ik vroeg me overigens af wat makkelijker is als ik nieuwe buggs vind of nieuwe features bedenk: Nieuwe reacties plaatsen, of het originele bericht aanpassen? Ik weet namelijk niet wanneer jij een (e-mail) notificatie krijgt

**Comment by Z3r0byte** [comment]
Bij nieuwe bugs vind ik het fijner als je een nieuwe issue opent, het liefst voor elke losse bug ook een losse issue. Zo blijft het voor mij ook overzichtelijker en kan ik losse bugs sluiten.

**Comment by ghost** [comment]
@Z3r0byte Oké dat zal ik doen! Geldt dit ook voor feature requests?

**Comment by Z3r0byte** [comment]
Het liefst wel ;)

Oh, goed nieuws trouwens de door jou gemelde bugs zijn gefixed. Helaas is er ook een kleine glitch bijgekomen :disappointed:

**Comment by ghost** [comment]
Oké zal ik doen! Vervelend van die glitch, wat is er mis?

**Comment by Z3r0byte** [comment]
Zwarte tekst in plaats van witte in de Toolbar in landscape mode

**Comment by Z3r0byte** [comment]
> Oh, goed nieuws trouwens de door jou gemelde bugs zijn gefixed.

Release komt trouwens morgen, er zijn wat problemen met Android Studio

**Comment by ghost** [comment]
>Zwarte tekst in plaats van witte in de toolbar in landscape mode

Oh dat is erg merkwaardig... Heb je al enig idee hoe je het gaat oplossen?

Trouwens: Ik zie net dat dit slechts hulpmiddelen voor magister zijn en dat het geen 'volledige' magister client is. Hierop zal ik mijn feature requests aanpassen want ik had dit nog niet eerder gezien

**Comment by ghost** [comment]
>Het liefst wel ;)

Ik heb alles nu opgedeeld in categorieën, waardoor er niet te veel issues zijn, maar waardoor het wel (ietwat) overzichtelijker is!

**Comment by Z3r0byte** [comment]
Nee, nog niet, maar ik moet nog eens een keer goed gaan googelen. ;) En ik wilde je inderdaad nog vertellen dat het een Magister toolkit is, maar je hebt het nu zelf al gelezen xD. En er zullen waarschijnlijk steeds meer functies bijkomen, dus misschien komt het ooit nog wel in de buurt van een volledige Magister app. :)

**Comment by ghost** [comment]
>Ik heb alles opgedeeld in categorieën.

Ik bedacht me net dat dit eigenlijk niet handig is omdat dit het hele punt van de overzichtelijkheid weghaald, ik zal ze opsplitsen!

**Comment by ghost** [comment]
Ik heb inmiddels alles verplaats naar aparte issues, zodat je individueel kunt zeggen wat je ervan vindt. Sorry voor de onduidelijkheid!

**Comment by Z3r0byte** [comment]
Top!
